<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Courses\Module'                        => __DIR__ . '/Module.php',
    'Courses\Controller\IndexController' => __DIR__ . '/src/Courses/Controller/IndexController.php',
    'Courses\Controller\CoureurController' => __DIR__ . '/src/Courses/Controller/CoureurController.php',
    'Courses\Controller\CourseController' => __DIR__ . '/src/Courses/Controller/CourseController.php',
    'CoursesTest\Framework\TestCase'        => __DIR__ . '/tests/Courses/Framework/TestCase.php',
    'CoursesTest\SampleTest'                => __DIR__ . '/tests/Courses/SampleTest.php',
);
