<?php 
echo $this->form()->openTag($formulaire);
echo $this->formhidden($formulaire->get('id'));
?>
    <?php echo $this->bootstrapformrow($formulaire->get('name')) ?>
    <?php echo $this->bootstrapformrow($formulaire->get('location')) ?>
    <?php echo $this->bootstrapformrow($formulaire->get('date')) ?>
    <?php echo $this->bootstrapformrow($formulaire->get('description')) ?>
    <?php echo $this->formrow($formulaire->get('btnEnvoi')->setAttribute('class','btn btn-success btn-lg')) ?>
<?php 
echo $this->form()->closeTag($formulaire);
?>
